[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[build]
command = "npm run lint && npm run build"
publish = "build"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
  package = "./.netlify/slack"

[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
    enable = false    

  [plugins.inputs.postBuild]
    enable = true
    record = true
    group = "built site"